/***********************************************************************************
* File:         TitleCorpus.cs                                                     *
* Contents:     Class TitleCorpus                                                  *
* Author:       Stanislav Koncvebovski (aka Bav) (stanislav@pikkatech.eu)          *
* Date:         2026-05-13 11:22                                                   *
* Version:      1.0                                                                *
* Copyright:    pikkatech.eu (www.pikkatech.eu)                                    *
***********************************************************************************/

namespace LoremPress.Corpora
{
	internal class TitleCorpus
	{
		#region "Corpora"
		/// <summary>
		/// List of adjectives.
		/// </summary>
		internal  static readonly string[] Adjectives =
												{
													"Abstract",
													"Ancestral",
													"Ancient",
													"Arcane",
													"Astral",
													"Asymmetric",
													"Autonomous",
													"Bright",
													"Broken",
													"Celestial",
													"Cerulean",
													"Concealed",
													"Crimson",
													"Dark",
													"Distant",
													"Dormant",
													"Dynamic",
													"Emergent",
													"Empty",
													"Encoded",
													"Encrypted",
													"Eternal",
													"Fading",
													"Forgotten",
													"Fragmentary",
													"Fragmented",
													"Frozen",
													"Golden",
													"Harmonic",
													"Hidden",
													"Infinite",
													"Invisible",
													"Iron",
													"Isolated",
													"Liminal",
													"Lost",
													"Lucid",
													"Lunar",
													"Magnetic",
													"Mechanical",
													"Monolithic",
													"Mutable",
													"Mythic",
													"Nocturnal",
													"Nomadic",
													"Obscure",
													"Obsidian",
													"Parallel",
													"Peripheral",
													"Polar",
													"Primal",
													"Primeval",
													"Quantum",
													"Radial",
													"Recursive",
													"Remote",
													"Residual",
													"Resonant",
													"Sacred",
													"Secret",
													"Shifting",
													"Silent",
													"Solar",
													"Spectral",
													"Stellar",
													"Subterranean",
													"Subtle",
													"Symbolic",
													"Synthetic",
													"Temporal",
													"Transient",
													"Translucent",
													"Unwritten",
													"Vanishing",
													"Vertical",
													"Volatile",
												};

		/// <summary>
		/// List of nouns.
		/// </summary>
		internal  static readonly string[] NounPlural =
												{
													"Archives",
													"Artifacts",
													"Atlases",
													"Blueprints",
													"Cathedrals",
													"Chronicles",
													"Cities",
													"Codes",
													"Constellations",
													"Constructs",
													"Coordinates",
													"Corridors",
													"Cycles",
													"Dimensions",
													"Disciplines",
													"Doctrines",
													"Dreams",
													"Echoes",
													"Empires",
													"Engines",
													"Entities",
													"Equations",
													"Equinoxes",
													"Expeditions",
													"Fields",
													"Forms",
													"Fragments",
													"Frontiers",
													"Gateways",
													"Geometries",
													"Horizons",
													"Infinities",
													"Inscriptions",
													"Labyrinths",
													"Languages",
													"Libraries",
													"Machines",
													"Maps",
													"Matrices",
													"Mechanisms",
													"Memories",
													"Mirrors",
													"Monuments",
													"Narratives",
													"Networks",
													"Objects",
													"Observations",
													"Observatories",
													"Orbits",
													"Orders",
													"Parallels",
													"Patterns",
													"Phenomena",
													"Principles",
													"Realms",
													"Records",
													"Revelations",
													"Rituals",
													"Ruins",
													"Sequences",
													"Signals",
													"Spaces",
													"Spectra",
													"Structures",
													"Symbols",
													"Systems",
													"Territories",
													"Theories",
													"Thresholds",
													"Translations",
													"Vectors",
													"Volumes",
													"Worlds",
												};

internal  static readonly string[] NounSingular =
{
	"Archive",
	"Artifact",
	"Atlas",
	"Blueprint",
	"Cathedral",
	"Chronicle",
	"City",
	"Code",
	"Constellation",
	"Construct",
	"Coordinate",
	"Corridor",
	"Cycle",
	"Dimension",
	"Discipline",
	"Doctrine",
	"Dream",
	"Echo",
	"Empire",
	"Engine",
	"Entity",
	"Equation",
	"Equinox",
	"Expedition",
	"Field",
	"Form",
	"Fragment",
	"Frontier",
	"Gateway",
	"Geometry",
	"Horizon",
	"Infinity",
	"Inscription",
	"Labyrinth",
	"Language",
	"Library",
	"Machine",
	"Map",
	"Matrix",
	"Mechanism",
	"Memory",
	"Mirror",
	"Monument",
	"Narrative",
	"Network",
	"Object",
	"Observation",
	"Observatory",
	"Orbit",
	"Order",
	"Parallel",
	"Pattern",
	"Phenomenon",
	"Principle",
	"Realm",
	"Record",
	"Revelation",
	"Ritual",
	"Ruin",
	"Sequence",
	"Signal",
	"Space",
	"Spectrum",
	"Structure",
	"Symbol",
	"System",
	"Territory",
	"Theory",
	"Threshold",
	"Translation",
	"Vector",
	"Volume",
	"World",
};

		/// <summary>
		/// List of connectors.
		/// Not used in present version.
		/// </summary>
		internal static readonly string[] Connectors = { "of", "and", "in" };

		/// <summary>
		/// List of academic templates.
		/// </summary>
		internal static readonly string[] AcademicTitleTemplates =
		{
			"On {Adj} {Noun}",
			"Studies in {Adj} {Noun}",
			"A Theory of {Adj} {Noun}",
			"Notes on {Adj} {Noun}",
			"Towards a Model of {Adj} {Noun}",
			"The Structure of {Adj} {Noun}",
			"Observations on {Adj} {Noun}",
			"A Framework for {Adj} {Noun}"
		};

		/// <summary>
		/// List of literary templates.
		/// </summary>
		internal static readonly string[] LiteraryTitleTemplates =
		{
			"The {Adj} {Noun}",
			"The {Noun} of {Adj} {Noun}",
			"In the {Adj} {Noun}",
			"Between {Adj} {Noun}",
			"A History of {Adj} {Noun}",
			"The Last {Adj} {Noun}",
			"Songs of {Adj} {Noun}",
			"Chronicle of {Adj} {Noun}",
			"The Book of {Adj} {Noun}"
		};

		/// <summary>
		/// List of SciFi templates.
		/// </summary>
		internal static readonly string[] SciFiTitleTemplates =
		{
			"{Adj} {Noun} Protocol",
			"{Adj} {Noun} System",
			"Field Report: {Adj} {Noun}",
			"Log Entry: {Adj} {Noun}",
			"{Noun} Classification: {Adj}",
			"Simulation of {Adj} {Noun}",
			"Model: {Adj} {Noun}",
			"Analysis of {Adj} {Noun}",
			"{Adj} {Noun} Interface"
		};
		#endregion


		
		internal static readonly string[] Verbs =
										{
											"reveals",
											"contains",
											"transforms",
											"observes",
											"crosses",
											"defines",
											"echoes",
											"extends",
											"reflects",
											"preserves",
											"constructs",
											"conceals"
										};

		internal static readonly string[] AcademicSentenceTemplates =
		{
			   "The {Adj} {NounSingular} {Verb} under controlled conditions.",
    "Several {Adj} {NounPlural} {Verb} within the experimental framework.",
    "The study {Verb} the behavior of {Adj} {NounPlural}.",
    "This paper {Verb} a model of {Adj} {NounPlural}.",
    "The results {Verb} a consistent pattern in {Adj} {NounPlural}.",
    "We observe that {Adj} {NounPlural} {Verb} over time.",
    "The analysis {Verb} the structure of {Adj} {NounPlural}.",
    "Empirical data {Verb} across multiple {Adj} {NounPlural}.",
    "The framework {Verb} interactions between {Adj} {NounPlural}.",
    "The model {Verb} predictions regarding {Adj} {NounPlural}.",
    "The system {Verb} when exposed to {Adj} {NounPlural}.",
    "Our findings suggest that {Adj} {NounPlural} {Verb} systematically.",
    "The literature {Verb} conflicting interpretations of {Adj} {NounPlural}.",
    "The experiment {Verb} a correlation between {Adj} {NounPlural}.",
    "This approach {Verb} existing theories of {Adj} {NounPlural}.",
    "The hypothesis {Verb} the dynamics of {Adj} {NounPlural}.",
    "Previous studies {Verb} similar {Adj} {NounPlural}.",
    "The data {Verb} a deviation in {Adj} {NounPlural}.",
    "The method {Verb} across different {Adj} {NounPlural}.",
    "We propose a model that {Verb} {Adj} {NounPlural}.",
    "The system {Verb} in response to {Adj} {NounPlural}.",
    "The structure {Verb} under varying {Adj} {NounPlural}.",
    "The analysis {Verb} limitations in current models of {Adj} {NounPlural}.",
    "The findings {Verb} implications for {Adj} {NounPlural}.",
    "The dataset {Verb} inconsistently across {Adj} {NounPlural}.",
    "The simulation {Verb} the evolution of {Adj} {NounPlural}.",
    "This study {Verb} foundational assumptions about {Adj} {NounPlural}.",
    "The theory {Verb} observed behaviors in {Adj} {NounPlural}.",
    "Experimental results {Verb} predicted {Adj} {NounPlural}.",
    "The model {Verb} additional constraints on {Adj} {NounPlural}.",
    "We analyze how {Adj} {NounPlural} {Verb} in complex systems.",
    "The research {Verb} new insights into {Adj} {NounPlural}.",
    "The methodology {Verb} reproducible patterns in {Adj} {NounPlural}.",
    "The system {Verb} hierarchical structures of {Adj} {NounPlural}.",
    "The evaluation {Verb} performance across {Adj} {NounPlural}.",
    "The approach {Verb} variability in {Adj} {NounPlural}.",
    "The model {Verb} temporal changes in {Adj} {NounPlural}.",
    "The study {Verb} cross-domain behavior of {Adj} {NounPlural}.",
    "The framework {Verb} statistical properties of {Adj} {NounPlural}.",
    "The results {Verb} theoretical expectations for {Adj} {NounPlural}.",
    "We conclude that {Adj} {NounPlural} {Verb} under constrained conditions."
		};

		internal static readonly string[] LiterarySentenceTemplates =
		{
   "The {Adj} {NounPlural} {Verb} in silence.",
    "Beyond the {Adj} {NounPlural}, something {Verb}.",
    "The {NounSingular} {Verb} through forgotten {NounPlural}.",
    "In the distance, the {Adj} {NounPlural} {Verb}.",
    "The memory of {Adj} {NounPlural} {Verb} softly.",
    "The world of {Adj} {NounPlural} slowly {Verb}.",
    "The {Adj} {NounSingular} {Verb} beneath fading light.",
    "Between the {Adj} {NounPlural}, echoes {Verb}.",
    "The last {Adj} {NounSingular} still {Verb}.",
    "Where the {Adj} {NounPlural} once {Verb}.",
    "The {NounPlural} of the past {Verb} quietly.",
    "A forgotten {NounSingular} {Verb} in the dark.",
    "The horizon of {Adj} {NounPlural} {Verb} endlessly.",
    "The {Adj} {NounPlural} {Verb} like distant thoughts.",
    "Under the {Adj} {NounSingular}, memories {Verb}.",
    "The silence {Verb} across {Adj} {NounPlural}.",
    "The {Adj} {NounPlural} never truly {Verb}.",
    "Something within the {Adj} {NounPlural} {Verb}.",
    "The wind {Verb} through {Adj} {NounPlural}.",
    "The city of {Adj} {NounPlural} {Verb} at night.",
    "The {NounSingular} {Verb} beyond understanding.",
    "The dream of {Adj} {NounPlural} slowly {Verb}.",
    "The {Adj} {NounPlural} still {Verb} in memory.",
    "In every shadow, the {Adj} {NounSingular} {Verb}.",
    "The forgotten {NounPlural} {Verb} again.",
    "The sky above {Adj} {NounPlural} {Verb}.",
    "The end of {Adj} {NounPlural} {Verb} quietly.",
    "The {Adj} {NounPlural} {Verb} into nothingness.",
    "A single {NounSingular} {Verb} through time.",
    "The memory of the {Adj} {NounSingular} {Verb} forever.",
    "The world beneath {Adj} {NounPlural} {Verb} slowly.",
    "The {Adj} {NounPlural} never stop to {Verb}.",
    "The night {Verb} over {Adj} {NounPlural}.",
    "The forgotten {NounSingular} still {Verb}.",
    "The echoes of {Adj} {NounPlural} {Verb} again.",
    "The {Adj} {NounPlural} fade as they {Verb}.",
    "The last trace of {Adj} {NounPlural} {Verb}.",
    "Time itself {Verb} through {Adj} {NounPlural}.",
    "The {NounPlural} of dreams {Verb} softly.",
    "The unseen {Adj} {NounPlural} always {Verb}.",
    "And so the {Adj} {NounPlural} {Verb} forever."
		};

		internal static readonly string[] TechnicalSentenceTemplates =
		{
		   "The {Adj} {NounSingular} {Verb} the {Adj} {NounSingular}.",
    "The {Adj} {NounPlural} {Verb} under controlled conditions.",
    "A {Adj} {NounSingular} {Verb} within the system.",
    "Several {Adj} {NounPlural} {Verb} in parallel.",
    "The system {Verb} {Adj} {NounPlural}.",
    "{Adj} {NounSingular} {Verb} the underlying {NounSingular}.",
    "The {NounSingular} {Verb} across multiple {NounPlural}.",
    "A {Adj} {NounSingular} {Verb} the data stream.",
    "Field tests show that {Adj} {NounPlural} {Verb} intermittently.",
    "The controller {Verb} the {Adj} {NounSingular}.",
    "{Adj} {NounPlural} {Verb} according to predefined rules.",
    "The architecture {Verb} {Adj} {NounPlural}.",
    "Each {NounSingular} {Verb} the next {NounSingular}.",
    "The process {Verb} within {Adj} {NounPlural}.",
    "{Adj} {NounSingular} often {Verb} unexpectedly.",
    "The system dynamically {Verb} {Adj} {NounPlural}.",
    "A failure occurs when the {NounSingular} {Verb}.",
    "{Adj} {NounPlural} consistently {Verb} in simulation.",
    "The engine {Verb} during high-load {NounPlural}.",
    "Each module {Verb} a corresponding {NounSingular}.",
    "The network {Verb} across distributed {NounPlural}.",
    "{Adj} {NounSingular} {Verb} state transitions.",
    "The algorithm {Verb} {Adj} {NounPlural}.",
    "Multiple {NounPlural} {Verb} simultaneously.",
    "The system occasionally {Verb} into unstable states.",
    "{Adj} {NounSingular} {Verb} when conditions change.",
    "Sensors {Verb} {Adj} {NounPlural} in real time.",
    "The framework {Verb} continuous streams of {NounPlural}.",
    "A {NounSingular} may {Verb} unexpectedly under stress.",
    "The controller frequently {Verb} during execution.",
    "{Adj} {NounPlural} {Verb} through layered subsystems.",
    "The model {Verb} complex {NounPlural}.",
    "The interface {Verb} user-defined {NounPlural}.",
    "Each iteration {Verb} the previous {NounSingular}.",
    "The pipeline {Verb} incoming {Adj} {NounPlural}.",
    "{Adj} {NounSingular} {Verb} and recalibrates continuously.",
    "The system {Verb} and adapts to {Adj} {NounPlural}.",
    "Logs indicate that {Adj} {NounPlural} {Verb} repeatedly.",
    "The architecture {Verb} without external intervention.",
    "Under load, the {NounSingular} {Verb} unpredictably."
		};
	}
}
