/***********************************************************************************
* File:         TitleCorpus.cs                                                     *
* Contents:     Class TitleCorpus                                                  *
* Author:       Stanislav Koncvebovski (aka Bav) (stanislav@pikkatech.eu)          *
* Date:         2026-05-13 11:22                                                   *
* Version:      1.0                                                                *
* Copyright:    pikkatech.eu (www.pikkatech.eu)                                    *
***********************************************************************************/

namespace LoremPress.Corpora
{
	internal class TitleCorpus
	{
		#region "Corpora"
		/// <summary>
		/// List of adjectives.
		/// </summary>
		internal  static readonly string[] Adjectives =
												{
													"Abstract",
													"Ancestral",
													"Ancient",
													"Arcane",
													"Astral",
													"Asymmetric",
													"Autonomous",
													"Bright",
													"Broken",
													"Celestial",
													"Cerulean",
													"Concealed",
													"Crimson",
													"Dark",
													"Distant",
													"Dormant",
													"Dynamic",
													"Emergent",
													"Empty",
													"Encoded",
													"Encrypted",
													"Eternal",
													"Fading",
													"Forgotten",
													"Fragmentary",
													"Fragmented",
													"Frozen",
													"Golden",
													"Harmonic",
													"Hidden",
													"Infinite",
													"Invisible",
													"Iron",
													"Isolated",
													"Liminal",
													"Lost",
													"Lucid",
													"Lunar",
													"Magnetic",
													"Mechanical",
													"Monolithic",
													"Mutable",
													"Mythic",
													"Nocturnal",
													"Nomadic",
													"Obscure",
													"Obsidian",
													"Parallel",
													"Peripheral",
													"Polar",
													"Primal",
													"Primeval",
													"Quantum",
													"Radial",
													"Recursive",
													"Remote",
													"Residual",
													"Resonant",
													"Sacred",
													"Secret",
													"Shifting",
													"Silent",
													"Solar",
													"Spectral",
													"Stellar",
													"Subterranean",
													"Subtle",
													"Symbolic",
													"Synthetic",
													"Temporal",
													"Transient",
													"Translucent",
													"Unwritten",
													"Vanishing",
													"Vertical",
													"Volatile",
												};

		/// <summary>
		/// List of nouns.
		/// </summary>
		internal  static readonly string[] NounPlural =
												{
													"Archives",
													"Artifacts",
													"Atlases",
													"Blueprints",
													"Cathedrals",
													"Chronicles",
													"Cities",
													"Codes",
													"Constellations",
													"Constructs",
													"Coordinates",
													"Corridors",
													"Cycles",
													"Dimensions",
													"Disciplines",
													"Doctrines",
													"Dreams",
													"Echoes",
													"Empires",
													"Engines",
													"Entities",
													"Equations",
													"Equinoxes",
													"Expeditions",
													"Fields",
													"Forms",
													"Fragments",
													"Frontiers",
													"Gateways",
													"Geometries",
													"Horizons",
													"Infinities",
													"Inscriptions",
													"Labyrinths",
													"Languages",
													"Libraries",
													"Machines",
													"Maps",
													"Matrices",
													"Mechanisms",
													"Memories",
													"Mirrors",
													"Monuments",
													"Narratives",
													"Networks",
													"Objects",
													"Observations",
													"Observatories",
													"Orbits",
													"Orders",
													"Parallels",
													"Patterns",
													"Phenomena",
													"Principles",
													"Realms",
													"Records",
													"Revelations",
													"Rituals",
													"Ruins",
													"Sequences",
													"Signals",
													"Spaces",
													"Spectra",
													"Structures",
													"Symbols",
													"Systems",
													"Territories",
													"Theories",
													"Thresholds",
													"Translations",
													"Vectors",
													"Volumes",
													"Worlds",
												};

internal  static readonly string[] NounSingular =
{
	"Archive",
	"Artifact",
	"Atlas",
	"Blueprint",
	"Cathedral",
	"Chronicle",
	"City",
	"Code",
	"Constellation",
	"Construct",
	"Coordinate",
	"Corridor",
	"Cycle",
	"Dimension",
	"Discipline",
	"Doctrine",
	"Dream",
	"Echo",
	"Empire",
	"Engine",
	"Entity",
	"Equation",
	"Equinox",
	"Expedition",
	"Field",
	"Form",
	"Fragment",
	"Frontier",
	"Gateway",
	"Geometry",
	"Horizon",
	"Infinity",
	"Inscription",
	"Labyrinth",
	"Language",
	"Library",
	"Machine",
	"Map",
	"Matrix",
	"Mechanism",
	"Memory",
	"Mirror",
	"Monument",
	"Narrative",
	"Network",
	"Object",
	"Observation",
	"Observatory",
	"Orbit",
	"Order",
	"Parallel",
	"Pattern",
	"Phenomenon",
	"Principle",
	"Realm",
	"Record",
	"Revelation",
	"Ritual",
	"Ruin",
	"Sequence",
	"Signal",
	"Space",
	"Spectrum",
	"Structure",
	"Symbol",
	"System",
	"Territory",
	"Theory",
	"Threshold",
	"Translation",
	"Vector",
	"Volume",
	"World",
};

		/// <summary>
		/// List of connectors.
		/// Not used in present version.
		/// </summary>
		internal static readonly string[] Connectors = { "of", "and", "in" };

		/// <summary>
		/// List of academic templates.
		/// </summary>
		internal static readonly string[] AcademicTitleTemplates =
		{
			"On {Adj} {Noun}",
			"Studies in {Adj} {Noun}",
			"A Theory of {Adj} {Noun}",
			"Notes on {Adj} {Noun}",
			"Towards a Model of {Adj} {Noun}",
			"The Structure of {Adj} {Noun}",
			"Observations on {Adj} {Noun}",
			"A Framework for {Adj} {Noun}"
		};

		/// <summary>
		/// List of literary templates.
		/// </summary>
		internal static readonly string[] LiteraryTitleTemplates =
		{
			"The {Adj} {Noun}",
			"The {Noun} of {Adj} {Noun}",
			"In the {Adj} {Noun}",
			"Between {Adj} {Noun}",
			"A History of {Adj} {Noun}",
			"The Last {Adj} {Noun}",
			"Songs of {Adj} {Noun}",
			"Chronicle of {Adj} {Noun}",
			"The Book of {Adj} {Noun}"
		};

		/// <summary>
		/// List of SciFi templates.
		/// </summary>
		internal static readonly string[] SciFiTitleTemplates =
		{
			"{Adj} {Noun} Protocol",
			"{Adj} {Noun} System",
			"Field Report: {Adj} {Noun}",
			"Log Entry: {Adj} {Noun}",
			"{Noun} Classification: {Adj}",
			"Simulation of {Adj} {Noun}",
			"Model: {Adj} {Noun}",
			"Analysis of {Adj} {Noun}",
			"{Adj} {Noun} Interface"
		};
		#endregion


		
		internal static readonly string[] Verbs =
										{
											"reveals",
											"contains",
											"transforms",
											"observes",
											"crosses",
											"defines",
											"echoes",
											"extends",
											"reflects",
											"preserves",
											"constructs",
											"conceals"
										};

		internal static readonly string[] AcademicSentenceTemplates =
		{
			"On {Adj} {NounSingular}",
			"Studies in {Adj} {NounPlural}",
			"A Theory of {Adj} {NounPlural}",
			"Observations on {Adj} {NounPlural}",
			"Towards a Model of {Adj} {NounPlural}",
			"A Framework for {Adj} {NounPlural}",
			"The Structure of {Adj} {NounPlural}",
			"Preliminary Notes on {Adj} {NounPlural}",
			"An Analysis of {Adj} {NounPlural}",
			"On the Dynamics of {Adj} {NounPlural}",
			"A Formal Description of {Adj} {NounPlural}",
			"Empirical Findings in {Adj} {NounPlural}",
			"Quantitative Approaches to {Adj} {NounPlural}",
			"On the Evolution of {Adj} {NounPlural}",
			"A Comparative Study of {Adj} {NounPlural}",
			"Methodological Aspects of {Adj} {NounPlural}",
			"A Taxonomy of {Adj} {NounPlural}",
			"The Role of {Adj} {NounPlural} in Complex Systems",
			"On the Stability of {Adj} {NounPlural}",
			"Interpreting {Adj} {NounPlural} under Variable Conditions",
			"Towards a Unified Theory of {Adj} {NounPlural}",
			"Reassessing Classical Models of {Adj} {NounPlural}",
			"On the Emergence of {Adj} {NounPlural}",
			"Structural Properties of {Adj} {NounPlural}",
			"A Probabilistic Model of {Adj} {NounPlural}",
			"Revisiting Assumptions in {Adj} {NounPlural}",
			"On the Classification of {Adj} {NounPlural}",
			"A Formalization of {Adj} {NounPlural}",
			"Notes on Boundary Conditions in {Adj} {NounPlural}",
			"Theoretical Extensions of {Adj} {NounPlural}",
			"On the Representation of {Adj} {NounPlural}",
			"A Model-Based Approach to {Adj} {NounPlural}",
			"Constraints in {Adj} {NounPlural}",
			"Towards Operational Definitions of {Adj} {NounPlural}",
			"Systemic Perspectives on {Adj} {NounPlural}",
			"On the Invariance of {Adj} {NounPlural}",
			"Hierarchical Structures in {Adj} {NounPlural}",
			"On the Formal Limits of {Adj} {NounPlural}",
			"A Synthesis of {Adj} {NounPlural} Theory",
			"Reconceptualizing {Adj} {NounPlural}"
		};

		internal static readonly string[] LiterarySentenceTemplates =
		{
			"The {Adj} {NounPlural}",
			"The {NounSingular} of {Adj} {NounPlural}",
			"In the {Adj} {NounSingular}",
			"Between {Adj} {NounPlural}",
			"Beyond the {Adj} {NounPlural}",
			"The Last {Adj} {NounSingular}",
			"Songs of {Adj} {NounPlural}",
			"Chronicles of {Adj} {NounPlural}",
			"The Book of {Adj} {NounPlural}",
			"Memories of {Adj} {NounPlural}",
			"The Silence of {Adj} {NounPlural}",
			"Where the {Adj} {NounPlural} End",
			"The Dream of {Adj} {NounPlural}",
			"Under the {Adj} {NounSingular}",
			"The Weight of {Adj} {NounPlural}",
			"Whispers from {Adj} {NounPlural}",
			"The Shape of {Adj} {NounPlural}",
			"Of {Adj} {NounPlural} and Shadows",
			"The Return of the {Adj} {NounSingular}",
			"The Forgotten {NounPlural}",
			"Echoes of {Adj} {NounPlural}",
			"The Age of {Adj} {NounPlural}",
			"When the {Adj} {NounPlural} Fell Silent",
			"The Hidden {NounPlural}",
			"Across the {Adj} {NounPlural}",
			"The Garden of {Adj} {NounPlural}",
			"The End of {Adj} {NounPlural}",
			"The Map of {Adj} {NounPlural}",
			"Songs Written in {Adj} {NounPlural}",
			"The Night of {Adj} {NounPlural}",
			"The Keeper of {Adj} {NounPlural}",
			"The Memory of {Adj} {NounSingular}",
			"Beneath the {Adj} {NounPlural}",
			"The Weightless {NounSingular}",
			"Tales of {Adj} {NounPlural}",
			"The Forgotten Book of {Adj} {NounPlural}",
			"The Horizon of {Adj} {NounPlural}",
			"The Quiet {NounPlural}",
			"The City of {Adj} {NounPlural}",
			"The Last Chronicle of {Adj} {NounPlural}"
		};

		internal static readonly string[] TechnicalSentenceTemplates =
		{
		   "{Adj} {NounSingular} Protocol",
			"{Adj} {NounSingular} System",
			"{Adj} {NounSingular} Engine",
			"{Adj} {NounSingular} Framework",
			"{Adj} {NounSingular} Interface",
			"{Adj} {NounSingular} Model",
			"{Adj} {NounSingular} Architecture",
			"Simulation of {Adj} {NounPlural}",
			"Analysis of {Adj} {NounPlural}",
			"Control of {Adj} {NounPlural}",
			"Monitoring {Adj} {NounPlural}",
			"Optimization of {Adj} {NounPlural}",
			"{NounSingular} Classification: {Adj}",
			"{NounSingular} Processing Unit",
			"Distributed {Adj} {NounPlural}",
			"Automated {Adj} {NounPlural}",
			"Adaptive {Adj} {NounSingular} Layer",
			"Dynamic {Adj} {NounSingular} Control",
			"Real-Time {Adj} {NounSingular} Processing",
			"Fault-Tolerant {Adj} {NounSingular}",
			"Scalable {Adj} {NounSingular} Network",
			"Recursive {Adj} {NounSingular} Algorithm",
			"Parallel {Adj} {NounSingular} Execution",
			"Event-Driven {Adj} {NounSingular} System",
			"Log Entry: {Adj} {NounSingular}",
			"Field Report: {Adj} {NounPlural}",
			"System Report on {Adj} {NounPlural}",
			"Initialization of {Adj} {NounSingular}",
			"Termination of {Adj} {NounSingular}",
			"Deployment of {Adj} {NounSingular}",
			"Validation of {Adj} {NounPlural}",
			"Error Handling in {Adj} {NounSingular}",
			"Diagnostics of {Adj} {NounPlural}",
			"Performance of {Adj} {NounSingular}",
			"Latency in {Adj} {NounPlural}",
			"Throughput of {Adj} {NounSingular}",
			"State Transition in {Adj} {NounSingular}",
			"Synchronization of {Adj} {NounPlural}",
			"Resource Allocation in {Adj} {NounSingular}",
			"System Integrity of {Adj} {NounSingular}"
		};
	}
}
